name: ec_carwash
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  pdf: ^3.10.7
  printing: ^5.12.0
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.1.4
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  flutter_local_notifications: ^18.0.1
  intl: ^0.19.0
  fl_chart: ^0.69.0
  file_picker: ^8.1.4
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/new_logo.png"  # your new logo

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Regular.ttf
        - asset: assets/Roboto-Bold.ttf
          weight: 700
